server:
  port: 8888
spring:
  datasource:
    username: root
    password: 963553
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource